-- ==========================================================================
-- F1 infographic — complete database setup
--
-- GENERATED by etl/scripts/gen-bundle.mjs — do not edit by hand.
-- Regenerate with: npm run db:bundle
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- Safe to re-run: every statement is idempotent.
--
-- Source files, in order:
--   db/migrations/0001_schema.sql
--   db/migrations/0002_views.sql
--   db/migrations/0003_policies.sql
--   db/seed/0010_seasons.sql
--   db/seed/0011_circuits.sql
--   db/seed/0012_constructors.sql
--   db/seed/0013_drivers.sql
--   db/seed/0014_driver_entries_2026.sql
--   db/seed/0015_races_2026.sql
-- ==========================================================================


-- ──────────────────────────────────────────────────────────────────────────
-- db/migrations/0001_schema.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- F1 infographic — core schema
-- Target: Supabase / PostgreSQL 15+
-- Idempotent: safe to re-run.
-- ============================================================================

create schema if not exists f1;
comment on schema f1 is 'Formula 1 reference data, session results and standings.';

-- ── Enums ───────────────────────────────────────────────────────────────────

do $$ begin
  create type f1.circuit_type as enum ('street', 'permanent', 'semi_permanent');
exception when duplicate_object then null; end $$;

do $$ begin
  create type f1.race_status as enum ('scheduled', 'completed', 'cancelled', 'postponed');
exception when duplicate_object then null; end $$;

-- Ordered chronologically within a race weekend so `order by session_type` is useful.
do $$ begin
  create type f1.session_type as enum (
    'fp1', 'fp2', 'fp3', 'sprint_qualifying', 'sprint', 'qualifying', 'race'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type f1.session_status as enum ('scheduled', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

-- ── Reference tables ────────────────────────────────────────────────────────

create table if not exists f1.seasons (
  year         smallint primary key check (year between 1950 and 2100),
  race_count   smallint,
  updated_at   timestamptz not null default now()
);

-- `id` is the slug the frontend already uses ("monaco", "lasvegas"), so the
-- page keeps its existing keys. ergast_circuit_id is the upstream join key.
create table if not exists f1.circuits (
  id                text primary key,
  ergast_circuit_id text unique,
  name              text not null,
  locality          text,
  country           text,
  flag_emoji        text,
  length_km         numeric(6,3),
  turns             smallint,
  circuit_type      f1.circuit_type,
  svg_path          text,
  lat               numeric(9,6),
  lng               numeric(9,6),
  updated_at        timestamptz not null default now()
);

create table if not exists f1.constructors (
  id          text primary key,             -- ergast constructorId
  name        text not null,
  nationality text,
  color       text check (color is null or color ~* '^#[0-9a-f]{6}$'),
  updated_at  timestamptz not null default now()
);

create table if not exists f1.drivers (
  id                    text primary key,   -- ergast driverId
  -- the key the single-file frontend renders by; disambiguates e.g. Michael
  -- Schumacher ("Schumacher") from Ralf Schumacher ("Ralf")
  display_key           text unique,
  code                  text,               -- 'VER'
  permanent_number      smallint,
  given_name            text,
  family_name           text not null,
  full_name             text generated always as
                          (trim(both ' ' from coalesce(given_name, '') || ' ' || family_name)) stored,
  nationality           text,
  date_of_birth         date,
  headshot_url          text,
  headshot_fallback_url text,
  updated_at            timestamptz not null default now()
);

create index if not exists drivers_family_name_idx on f1.drivers (lower(family_name));

-- A driver's team and car number are season-scoped, not driver-scoped. The old
-- single-file DRIVERS const conflated the two; this table separates them.
create table if not exists f1.driver_entries (
  season_year    smallint not null references f1.seasons(year) on delete cascade,
  driver_id      text     not null references f1.drivers(id)   on delete cascade,
  constructor_id text     not null references f1.constructors(id) on delete cascade,
  car_number     smallint,
  primary key (season_year, driver_id, constructor_id)
);

create index if not exists driver_entries_season_idx on f1.driver_entries (season_year);

-- ── Events ──────────────────────────────────────────────────────────────────

create table if not exists f1.races (
  id                bigint generated always as identity primary key,
  season_year       smallint not null references f1.seasons(year) on delete cascade,
  round             smallint not null check (round > 0),
  circuit_id        text     not null references f1.circuits(id),
  name              text     not null,          -- "Monaco GP"
  official_name     text,                       -- upstream raceName
  race_date         date,
  race_time         time,
  starts_at         timestamptz,
  date_label        text,                       -- display string, e.g. "5–7 Jun"
  scheduled_laps    smallint,
  is_sprint_weekend boolean  not null default false,
  status            f1.race_status not null default 'scheduled',
  wikipedia_url     text,
  updated_at        timestamptz not null default now(),
  unique (season_year, round)
);

create index if not exists races_circuit_idx on f1.races (circuit_id, season_year desc);
create index if not exists races_date_idx    on f1.races (race_date);

create table if not exists f1.sessions (
  id                bigint generated always as identity primary key,
  race_id           bigint not null references f1.races(id) on delete cascade,
  session_type      f1.session_type not null,
  starts_at         timestamptz,
  openf1_session_key integer unique,
  status            f1.session_status not null default 'scheduled',
  results_count     smallint not null default 0,
  updated_at        timestamptz not null default now(),
  unique (race_id, session_type)
);

create index if not exists sessions_race_idx on f1.sessions (race_id, session_type);

-- One row per driver per session. Columns are a superset across session types:
-- race/sprint use points/grid/laps_completed/status, qualifying uses q1..q3,
-- practice uses best_lap_ms. Nulls elsewhere.
create table if not exists f1.session_results (
  id                  bigint generated always as identity primary key,
  session_id          bigint not null references f1.sessions(id) on delete cascade,
  driver_id           text   not null references f1.drivers(id),
  constructor_id      text   references f1.constructors(id),
  position            smallint,
  position_text       text,                   -- 'R', 'D', 'W', 'NC' or the number
  car_number          smallint,
  grid                smallint,
  laps_completed      smallint,
  status              text,                   -- 'Finished', '+1 Lap', 'Collision'
  points              numeric(5,2) not null default 0,
  time_text           text,                   -- '1:23:06.802' as published
  time_ms             bigint,
  gap_text            text,                   -- '+2.974' / '+1 Lap'
  gap_ms              bigint,
  best_lap_ms         integer,                -- practice / sprint-shootout best
  q1_ms               integer,
  q2_ms               integer,
  q3_ms               integer,
  fastest_lap_ms      integer,
  fastest_lap_number  smallint,
  fastest_lap_rank    smallint,
  fastest_lap_kph     numeric(6,3),
  updated_at          timestamptz not null default now(),
  unique (session_id, driver_id)
);

create index if not exists session_results_session_pos_idx
  on f1.session_results (session_id, position nulls last);
create index if not exists session_results_driver_idx
  on f1.session_results (driver_id);

-- Heaviest table: one row per driver per lap (OpenF1, 2023+).
create table if not exists f1.lap_times (
  session_id  bigint   not null references f1.sessions(id) on delete cascade,
  driver_id   text     not null references f1.drivers(id),
  lap_number  smallint not null,
  lap_ms      integer,
  sector1_ms  integer,
  sector2_ms  integer,
  sector3_ms  integer,
  is_pit_out  boolean not null default false,
  is_pit_in   boolean not null default false,
  position    smallint,
  primary key (session_id, driver_id, lap_number)
);

create index if not exists lap_times_session_best_idx
  on f1.lap_times (session_id, lap_ms) where lap_ms is not null;

-- ── Standings (snapshot after each round) ───────────────────────────────────

create table if not exists f1.driver_standings (
  season_year    smallint not null references f1.seasons(year) on delete cascade,
  round          smallint not null,
  driver_id      text     not null references f1.drivers(id),
  constructor_id text     references f1.constructors(id),
  position       smallint,
  points         numeric(6,2) not null default 0,
  wins           smallint not null default 0,
  updated_at     timestamptz not null default now(),
  primary key (season_year, round, driver_id)
);

create table if not exists f1.constructor_standings (
  season_year    smallint not null references f1.seasons(year) on delete cascade,
  round          smallint not null,
  constructor_id text     not null references f1.constructors(id),
  position       smallint,
  points         numeric(6,2) not null default 0,
  wins           smallint not null default 0,
  updated_at     timestamptz not null default now(),
  primary key (season_year, round, constructor_id)
);

-- ── ETL bookkeeping ─────────────────────────────────────────────────────────

create table if not exists f1.ingest_runs (
  id           bigint generated always as identity primary key,
  source       text not null,               -- 'jolpica' | 'openf1'
  scope        text not null,               -- '2026:results', '2026:r16:laps', ...
  started_at   timestamptz not null default now(),
  finished_at  timestamptz,
  status       text not null default 'running' check (status in ('running','ok','error')),
  rows_written integer not null default 0,
  error        text
);

create index if not exists ingest_runs_recent_idx on f1.ingest_runs (started_at desc);

-- ── updated_at triggers ─────────────────────────────────────────────────────

create or replace function f1.touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

do $$
declare t text;
begin
  foreach t in array array[
    'seasons','circuits','constructors','drivers','races','sessions',
    'session_results','driver_standings','constructor_standings'
  ] loop
    execute format('drop trigger if exists touch_%1$s on f1.%1$s', t);
    execute format(
      'create trigger touch_%1$s before update on f1.%1$s
         for each row execute function f1.touch_updated_at()', t);
  end loop;
end $$;


-- ──────────────────────────────────────────────────────────────────────────
-- db/migrations/0002_views.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- Read API for the frontend.
--
-- Views live in `public` (not `f1`) so the anon key can reach them over
-- PostgREST without changing Supabase's "Exposed schemas" setting.
-- security_invoker = true makes them respect the RLS policies in 0003.
-- ============================================================================

-- 2026 calendar, plus everything a race card needs to render before any
-- session data is loaded.
create or replace view public.f1_race_calendar
with (security_invoker = true) as
select
  r.id                as race_id,
  r.season_year,
  r.round,
  r.name,
  r.official_name,
  r.race_date,
  r.starts_at,
  r.date_label,
  r.scheduled_laps,
  r.is_sprint_weekend,
  r.status,
  c.id                as circuit_id,
  c.name              as circuit_name,
  c.locality,
  c.country,
  c.flag_emoji,
  c.length_km,
  c.turns,
  c.circuit_type,
  c.svg_path,
  -- true once the race weekend is in the past and we hold classified results
  exists (
    select 1 from f1.sessions s
     where s.race_id = r.id and s.session_type = 'race' and s.results_count > 0
  ) as has_results
from f1.races r
join f1.circuits c on c.id = r.circuit_id;

-- Denormalised classification. One row per driver per session, carrying the
-- display fields (family name, team colour, headshot) the page renders.
create or replace view public.f1_session_results
with (security_invoker = true) as
select
  r.season_year,
  r.round,
  r.circuit_id,
  s.id             as session_id,
  s.session_type,
  s.status         as session_status,
  sr.position,
  sr.position_text,
  sr.car_number,
  sr.grid,
  sr.laps_completed,
  sr.status        as result_status,
  sr.points,
  sr.time_text,
  sr.time_ms,
  sr.gap_text,
  sr.gap_ms,
  sr.best_lap_ms,
  sr.q1_ms, sr.q2_ms, sr.q3_ms,
  sr.fastest_lap_ms,
  sr.fastest_lap_rank,
  d.id             as driver_id,
  d.display_key,
  d.given_name,
  d.family_name,
  d.full_name,
  d.code           as driver_code,
  d.headshot_url,
  d.headshot_fallback_url,
  ct.id            as constructor_id,
  ct.name          as constructor_name,
  ct.color         as constructor_color
from f1.session_results sr
join f1.sessions s  on s.id = sr.session_id
join f1.races    r  on r.id = s.race_id
join f1.drivers  d  on d.id = sr.driver_id
left join f1.constructors ct on ct.id = sr.constructor_id;

-- Replaces the HISTORY const: top 3 of every race, every season.
create or replace view public.f1_race_podiums
with (security_invoker = true) as
select
  season_year,
  round,
  circuit_id,
  position,
  driver_id,
  display_key,
  family_name,
  full_name,
  constructor_id,
  constructor_name,
  constructor_color,
  time_text,
  gap_text,
  points
from public.f1_session_results
where session_type = 'race'
  and position between 1 and 3;

-- Championship state after the most recent scored round of each season.
create or replace view public.f1_driver_standings
with (security_invoker = true) as
select
  ds.season_year,
  ds.round,
  ds.position,
  ds.points,
  ds.wins,
  d.id   as driver_id,
  d.display_key,
  d.family_name,
  d.full_name,
  d.code as driver_code,
  d.headshot_url,
  ct.id   as constructor_id,
  ct.name as constructor_name,
  ct.color as constructor_color
from f1.driver_standings ds
join f1.drivers d on d.id = ds.driver_id
left join f1.constructors ct on ct.id = ds.constructor_id;

create or replace view public.f1_constructor_standings
with (security_invoker = true) as
select
  cs.season_year,
  cs.round,
  cs.position,
  cs.points,
  cs.wins,
  ct.id    as constructor_id,
  ct.name  as constructor_name,
  ct.color as constructor_color
from f1.constructor_standings cs
join f1.constructors ct on ct.id = cs.constructor_id;

-- Latest standings per season, so the page can query without knowing the round.
create or replace view public.f1_driver_standings_latest
with (security_invoker = true) as
select s.*
from public.f1_driver_standings s
join (
  select season_year, max(round) as round
  from f1.driver_standings group by season_year
) last on last.season_year = s.season_year and last.round = s.round;

create or replace view public.f1_constructor_standings_latest
with (security_invoker = true) as
select s.*
from public.f1_constructor_standings s
join (
  select season_year, max(round) as round
  from f1.constructor_standings group by season_year
) last on last.season_year = s.season_year and last.round = s.round;

-- Per-session lap pace summary, for practice charts without shipping every lap.
create or replace view public.f1_session_lap_summary
with (security_invoker = true) as
select
  lt.session_id,
  lt.driver_id,
  d.family_name,
  count(*)                                as laps,
  min(lt.lap_ms) filter (where lt.lap_ms is not null) as best_lap_ms,
  round(avg(lt.lap_ms) filter (
    where lt.lap_ms is not null and not lt.is_pit_in and not lt.is_pit_out
  ))                                      as avg_clean_lap_ms
from f1.lap_times lt
join f1.drivers d on d.id = lt.driver_id
group by lt.session_id, lt.driver_id, d.family_name;


-- ──────────────────────────────────────────────────────────────────────────
-- db/migrations/0003_policies.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- Row Level Security.
--
-- The site is public and read-only; every write goes through the ETL, which
-- authenticates with the service-role key and bypasses RLS entirely.
-- So: anon/authenticated get SELECT on everything, and nothing else.
-- ============================================================================

grant usage on schema f1 to anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array[
    'seasons','circuits','constructors','drivers','driver_entries',
    'races','sessions','session_results','lap_times',
    'driver_standings','constructor_standings','ingest_runs'
  ] loop
    execute format('alter table f1.%I enable row level security', t);
    execute format('drop policy if exists public_read on f1.%I', t);
    execute format('revoke all on f1.%I from anon, authenticated', t);
  end loop;
end $$;

-- Public read on the data tables.
do $$
declare t text;
begin
  foreach t in array array[
    'seasons','circuits','constructors','drivers','driver_entries',
    'races','sessions','session_results','lap_times',
    'driver_standings','constructor_standings'
  ] loop
    execute format('grant select on f1.%I to anon, authenticated', t);
    execute format(
      'create policy public_read on f1.%I for select to anon, authenticated using (true)', t);
  end loop;
end $$;

-- ingest_runs stays private: RLS is on with no policy, so anon sees nothing
-- even if the table is ever granted by accident.

-- The read views in 0002 are security_invoker, so they inherit the policies above.
grant select on
  public.f1_race_calendar,
  public.f1_session_results,
  public.f1_race_podiums,
  public.f1_driver_standings,
  public.f1_constructor_standings,
  public.f1_driver_standings_latest,
  public.f1_constructor_standings_latest,
  public.f1_session_lap_summary
to anon, authenticated;

-- Future tables in f1 must not leak by default.
alter default privileges in schema f1 revoke all on tables from anon, authenticated;


-- ──────────────────────────────────────────────────────────────────────────
-- db/seed/0010_seasons.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ==========================================================================
-- Seasons
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.seasons (year) values
  (2000),
  (2001),
  (2002),
  (2003),
  (2004),
  (2005),
  (2006),
  (2007),
  (2008),
  (2009),
  (2010),
  (2011),
  (2012),
  (2013),
  (2014),
  (2015),
  (2016),
  (2017),
  (2018),
  (2019),
  (2020),
  (2021),
  (2022),
  (2023),
  (2024),
  (2025),
  (2026)
on conflict (year) do nothing;


-- ──────────────────────────────────────────────────────────────────────────
-- db/seed/0011_circuits.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ==========================================================================
-- Circuits — names, location and geometry
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.circuits
  (id, ergast_circuit_id, name, locality, country, flag_emoji,
   length_km, turns, circuit_type)
values
  ('australia', 'albert_park', 'Melbourne', 'Melbourne', 'Australia', '🇦🇺', 5.278, 14, 'street'::f1.circuit_type),
  ('china', 'shanghai', 'Shanghai', 'Shanghai', 'China', '🇨🇳', 5.451, 16, 'permanent'::f1.circuit_type),
  ('japan', 'suzuka', 'Suzuka', 'Suzuka', 'Japan', '🇯🇵', 5.807, 18, 'permanent'::f1.circuit_type),
  ('bahrain', 'bahrain', 'Sakhir', 'Sakhir', 'Bahrain', '🇧🇭', 5.412, 15, 'permanent'::f1.circuit_type),
  ('saudi', 'jeddah', 'Jeddah', 'Jeddah', 'Saudi Arabia', '🇸🇦', 6.174, 27, 'street'::f1.circuit_type),
  ('miami', 'miami', 'Miami Gardens', 'Miami Gardens', 'USA', '🇺🇸', 5.412, 19, 'semi_permanent'::f1.circuit_type),
  ('canada', 'villeneuve', 'Montréal', 'Montréal', 'Canada', '🇨🇦', 4.361, 14, 'semi_permanent'::f1.circuit_type),
  ('monaco', 'monaco', 'Monte Carlo', 'Monte Carlo', 'Monaco', '🇲🇨', 3.337, 19, 'street'::f1.circuit_type),
  ('spain', 'catalunya', 'Barcelona', 'Barcelona', 'Spain', '🇪🇸', 4.675, 14, 'permanent'::f1.circuit_type),
  ('austria', 'red_bull_ring', 'Spielberg', 'Spielberg', 'Austria', '🇦🇹', 4.318, 10, 'permanent'::f1.circuit_type),
  ('britain', 'silverstone', 'Silverstone', 'Silverstone', 'Great Britain', '🇬🇧', 5.891, 18, 'permanent'::f1.circuit_type),
  ('belgium', 'spa', 'Spa-Francorchamps', 'Spa-Francorchamps', 'Belgium', '🇧🇪', 7.004, 19, 'permanent'::f1.circuit_type),
  ('hungary', 'hungaroring', 'Budapest', 'Budapest', 'Hungary', '🇭🇺', 4.381, 14, 'permanent'::f1.circuit_type),
  ('netherlands', 'zandvoort', 'Zandvoort', 'Zandvoort', 'Netherlands', '🇳🇱', 4.259, 14, 'permanent'::f1.circuit_type),
  ('italy', 'monza', 'Monza', 'Monza', 'Italy', '🇮🇹', 5.793, 11, 'permanent'::f1.circuit_type),
  ('madrid', 'madring', 'Madrid', 'Madrid', 'Spain', '🇪🇸', 5.47, 20, 'street'::f1.circuit_type),
  ('azerbaijan', 'baku', 'Baku', 'Baku', 'Azerbaijan', '🇦🇿', 6.003, 20, 'street'::f1.circuit_type),
  ('singapore', 'marina_bay', 'Marina Bay', 'Marina Bay', 'Singapore', '🇸🇬', 4.94, 19, 'street'::f1.circuit_type),
  ('usa', 'americas', 'Austin', 'Austin', 'USA', '🇺🇸', 5.513, 20, 'permanent'::f1.circuit_type),
  ('mexico', 'rodriguez', 'Mexico City', 'Mexico City', 'Mexico', '🇲🇽', 4.304, 17, 'permanent'::f1.circuit_type),
  ('brazil', 'interlagos', 'São Paulo', 'São Paulo', 'Brazil', '🇧🇷', 4.309, 15, 'permanent'::f1.circuit_type),
  ('lasvegas', 'vegas', 'Las Vegas', 'Las Vegas', 'USA', '🇺🇸', 6.201, 17, 'street'::f1.circuit_type),
  ('qatar', 'losail', 'Lusail', 'Lusail', 'Qatar', '🇶🇦', 5.38, 16, 'permanent'::f1.circuit_type),
  ('abudhabi', 'yas_marina', 'Yas Marina', 'Yas Marina', 'UAE', '🇦🇪', 5.281, 16, 'permanent'::f1.circuit_type)
on conflict (id) do update set
  ergast_circuit_id = excluded.ergast_circuit_id,
  name              = excluded.name,
  locality          = excluded.locality,
  country           = excluded.country,
  flag_emoji        = excluded.flag_emoji,
  length_km         = excluded.length_km,
  turns             = excluded.turns,
  circuit_type      = excluded.circuit_type;


-- ──────────────────────────────────────────────────────────────────────────
-- db/seed/0012_constructors.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ==========================================================================
-- Constructors — display names and livery colours
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.constructors (id, name, color)
values
  ('mercedes', 'Mercedes', '#00D7B6'),
  ('ferrari', 'Ferrari', '#ED1131'),
  ('mclaren', 'McLaren', '#F47600'),
  ('red_bull', 'Red Bull', '#4781D7'),
  ('williams', 'Williams', '#00A0DE'),
  ('aston_martin', 'Aston Martin', '#229971'),
  ('cadillac', 'Cadillac', '#909090'),
  ('audi', 'Audi', '#F50537'),
  ('haas', 'Haas', '#B6BABD'),
  ('alpine', 'Alpine', '#00A1E8'),
  ('rb', 'RB', '#6692FF'),
  ('alfa', 'Alfa Romeo', '#900000'),
  ('force_india', 'Force India', '#FF80C7'),
  ('renault', 'Renault', '#FFF500'),
  ('bar', 'BAR', '#D40000'),
  ('jordan', 'Jordan', '#FFD700'),
  ('bmw_sauber', 'BMW', '#0055A5'),
  ('brawn', 'Brawn GP', '#B8FD6E')
on conflict (id) do update set
  name  = excluded.name,
  color = coalesce(excluded.color, f1.constructors.color);


-- ──────────────────────────────────────────────────────────────────────────
-- db/seed/0013_drivers.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ==========================================================================
-- Drivers — headshots and display keys (names filled in by the ETL)
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.drivers
  (id, display_key, family_name, permanent_number, headshot_url, headshot_fallback_url)
values
  ('antonelli', 'Antonelli', 'Antonelli', 12, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/ANDANT01_Kimi_Antonelli/andant01.png.transform/2col/image.png', null),
  ('russell', 'Russell', 'Russell', 63, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/russell.svg', 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUSS01_George_Russell/georuss01.png.transform/1col/image.png'),
  ('leclerc', 'Leclerc', 'Leclerc', 16, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/2col/image.png', null),
  ('hamilton', 'Hamilton', 'Hamilton', 44, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/2col/image.png', null),
  ('norris', 'Norris', 'Norris', 1, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/2col/image.png', null),
  ('piastri', 'Piastri', 'Piastri', 81, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png.transform/2col/image.png', null),
  ('max_verstappen', 'Verstappen', 'Verstappen', 3, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/2col/image.png', null),
  ('hadjar', 'Hadjar', 'Hadjar', 6, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/I/ISAHAD01_Isack_Hadjar/isahad01.png.transform/2col/image.png', null),
  ('sainz', 'Sainz', 'Sainz', 55, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/2col/image.png', null),
  ('alonso', 'Alonso', 'Alonso', 14, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/2col/image.png', null),
  ('perez', 'Perez', 'Perez', 11, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/2col/image.png', null),
  ('hulkenberg', 'Hulkenberg', 'Hulkenberg', 27, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png.transform/2col/image.png', null),
  ('ocon', 'Ocon', 'Ocon', 31, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCON01_Esteban_Ocon/estocon01.png.transform/2col/image.png', null),
  ('gasly', 'Gasly', 'Gasly', 10, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIERGAS01_Pierre_Gasly/piergas01.png.transform/2col/image.png', null),
  ('albon', 'Albon', 'Albon', 23, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png.transform/2col/image.png', null),
  ('stroll', 'Stroll', 'Stroll', 18, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/2col/image.png', null),
  ('bottas', 'Bottas', 'Bottas', 77, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/2col/image.png', null),
  ('ricciardo', 'Ricciardo', 'Ricciardo', 3, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png.transform/2col/image.png', null),
  ('vettel', 'Vettel', 'Vettel', 5, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SEBVET01_Sebastian_Vettel/sebvet01.png.transform/2col/image.png', null),
  ('raikkonen', 'Raikkonen', 'Raikkonen', 7, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KIMRAI01_Kimi_Raikkonen/kimrai01.png.transform/2col/image.png', null),
  ('rosberg', 'Rosberg', 'Rosberg', 6, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICROS01_Nico_Rosberg/nicros01.png.transform/2col/image.png', null),
  ('kevin_magnussen', 'Magnussen', 'Magnussen', 20, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KEVMAG01_Kevin_Magnussen/kevmag01.png.transform/2col/image.png', null),
  ('tsunoda', 'Tsunoda', 'Tsunoda', 22, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png.transform/2col/image.png', null),
  ('lawson', 'Lawson', 'Lawson', 30, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LIALAW01_Liam_Lawson/lialaw01.png.transform/2col/image.png', null),
  ('kvyat', 'Kvyat', 'Kvyat', 26, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANKVYA01_Daniil_Kvyat/dankvya01.png.transform/2col/image.png', null),
  ('giovinazzi', 'Giovinazzi', 'Giovinazzi', 99, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ANTGIO01_Antonio_Giovinazzi/antgio01.png.transform/2col/image.png', null),
  ('zhou', 'Zhou', 'Zhou', 24, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GUAZHO01_Guanyu_Zhou/guazho01.png.transform/2col/image.png', null),
  ('latifi', 'Latifi', 'Latifi', 6, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICLAT01_Nicholas_Latifi/niclat01.png.transform/2col/image.png', null),
  ('grosjean', 'Grosjean', 'Grosjean', 8, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/R/ROMGRO01_Romain_Grosjean/romgro01.png.transform/2col/image.png', null),
  ('maldonado', 'Maldonado', 'Maldonado', 16, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PASMAL01_Pastor_Maldonado/pasmal01.png.transform/2col/image.png', null),
  ('sutil', 'Sutil', 'Sutil', 14, 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ADRSUT01_Adrian_Sutil/adrsut01.png.transform/2col/image.png', null),
  ('michael_schumacher', 'Schumacher', 'Schumacher', 1, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/schumacher.svg', null),
  ('barrichello', 'Barrichello', 'Barrichello', 2, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/barrichello.svg', null),
  ('coulthard', 'Coulthard', 'Coulthard', 5, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/coulthard.svg', null),
  ('hakkinen', 'Hakkinen', 'Hakkinen', 1, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/hakkinen.svg', null),
  ('montoya', 'Montoya', 'Montoya', 3, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/montoya.svg', null),
  ('trulli', 'Trulli', 'Trulli', 7, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/trulli.svg', null),
  ('fisichella', 'Fisichella', 'Fisichella', 9, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/fisichella.svg', null),
  ('irvine', 'Irvine', 'Irvine', 4, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/irvine.svg', null),
  ('villeneuve', 'Villeneuve', 'Villeneuve', 22, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/villeneuve.svg', null),
  ('ralf_schumacher', 'Ralf', 'Ralf', 5, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/ralf.svg', null),
  ('frentzen', 'Frentzen', 'Frentzen', 7, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/frentzen.svg', null),
  ('heidfeld', 'Heidfeld', 'Heidfeld', 5, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/heidfeld.svg', null),
  ('kovalainen', 'Kovalainen', 'Kovalainen', 23, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/kovalainen.svg', null),
  ('kubica', 'Kubica', 'Kubica', 7, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/kubica.svg', null),
  ('button', 'Button', 'Button', 22, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/button.svg', null),
  ('webber', 'Webber', 'Webber', 2, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/webber.svg', null),
  ('massa', 'Massa', 'Massa', 6, 'https://raw.githubusercontent.com/BahaaAhmed-Hub/f1/main/imgs/massa.svg', null)
on conflict (id) do update set
  display_key           = excluded.display_key,
  permanent_number      = coalesce(excluded.permanent_number, f1.drivers.permanent_number),
  headshot_url          = coalesce(excluded.headshot_url, f1.drivers.headshot_url),
  headshot_fallback_url = coalesce(excluded.headshot_fallback_url, f1.drivers.headshot_fallback_url);


-- ──────────────────────────────────────────────────────────────────────────
-- db/seed/0014_driver_entries_2026.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ==========================================================================
-- 2026 grid — driver / team / car number
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.driver_entries (season_year, driver_id, constructor_id, car_number)
values
  (2026, 'antonelli', 'mercedes', 12),
  (2026, 'russell', 'mercedes', 63),
  (2026, 'leclerc', 'ferrari', 16),
  (2026, 'hamilton', 'ferrari', 44),
  (2026, 'norris', 'mclaren', 1),
  (2026, 'piastri', 'mclaren', 81),
  (2026, 'max_verstappen', 'red_bull', 3),
  (2026, 'hadjar', 'red_bull', 6),
  (2026, 'sainz', 'williams', 55),
  (2026, 'alonso', 'aston_martin', 14),
  (2026, 'perez', 'cadillac', 11),
  (2026, 'hulkenberg', 'audi', 27),
  (2026, 'ocon', 'haas', 31),
  (2026, 'gasly', 'alpine', 10),
  (2026, 'albon', 'williams', 23),
  (2026, 'stroll', 'aston_martin', 18)
on conflict (season_year, driver_id, constructor_id) do update set
  car_number = excluded.car_number;


-- ──────────────────────────────────────────────────────────────────────────
-- db/seed/0015_races_2026.sql
-- ──────────────────────────────────────────────────────────────────────────
-- ==========================================================================
-- 2026 calendar — 24 rounds
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.races
  (season_year, round, circuit_id, name, date_label, race_date, scheduled_laps,
   is_sprint_weekend, status)
values
  (2026, 1, 'australia', 'Australian GP', '6–8 Mar', '2026-03-08', 58, false, 'completed'::f1.race_status),
  (2026, 2, 'china', 'Chinese GP', '13–15 Mar', '2026-03-15', 56, true, 'completed'::f1.race_status),
  (2026, 3, 'japan', 'Japanese GP', '27–29 Mar', '2026-03-29', 53, false, 'completed'::f1.race_status),
  (2026, 4, 'bahrain', 'Bahrain GP', '10–12 Apr', '2026-04-12', 57, false, 'cancelled'::f1.race_status),
  (2026, 5, 'saudi', 'Saudi Arabian GP', '17–19 Apr', '2026-04-19', 50, false, 'cancelled'::f1.race_status),
  (2026, 6, 'miami', 'Miami GP', '1–3 May', '2026-05-03', 57, true, 'completed'::f1.race_status),
  (2026, 7, 'canada', 'Canadian GP', '22–24 May', '2026-05-24', 70, true, 'completed'::f1.race_status),
  (2026, 8, 'monaco', 'Monaco GP', '5–7 Jun', '2026-06-07', 78, false, 'completed'::f1.race_status),
  (2026, 9, 'spain', 'Barcelona-Catalunya GP', '12–14 Jun', '2026-06-14', 66, false, 'completed'::f1.race_status),
  (2026, 10, 'austria', 'Austrian GP', '26–28 Jun', '2026-06-28', 71, false, 'completed'::f1.race_status),
  (2026, 11, 'britain', 'British GP', '3–5 Jul', '2026-07-05', 52, true, 'completed'::f1.race_status),
  (2026, 12, 'belgium', 'Belgian GP', '17–19 Jul', '2026-07-19', 44, false, 'completed'::f1.race_status),
  (2026, 13, 'hungary', 'Hungarian GP', '24–26 Jul', '2026-07-26', 70, false, 'completed'::f1.race_status),
  (2026, 14, 'netherlands', 'Dutch GP', '21–23 Aug', '2026-08-23', 72, true, 'completed'::f1.race_status),
  (2026, 15, 'italy', 'Italian GP', '4–6 Sep', '2026-09-06', 53, false, 'completed'::f1.race_status),
  (2026, 16, 'madrid', 'Madrid GP', '11–13 Sep', '2026-09-13', 56, false, 'completed'::f1.race_status),
  (2026, 17, 'azerbaijan', 'Azerbaijan GP', '25–27 Sep', '2026-09-27', 51, false, 'scheduled'::f1.race_status),
  (2026, 18, 'singapore', 'Singapore GP', '9–11 Oct', '2026-10-11', 62, true, 'scheduled'::f1.race_status),
  (2026, 19, 'usa', 'US GP', '23–25 Oct', '2026-10-25', 56, false, 'scheduled'::f1.race_status),
  (2026, 20, 'mexico', 'Mexico City GP', '30 Oct–1 Nov', '2026-11-01', 71, false, 'scheduled'::f1.race_status),
  (2026, 21, 'brazil', 'Brazilian GP', '6–8 Nov', '2026-11-08', 71, false, 'scheduled'::f1.race_status),
  (2026, 22, 'lasvegas', 'Las Vegas GP', '19–21 Nov', '2026-11-21', 50, false, 'scheduled'::f1.race_status),
  (2026, 23, 'qatar', 'Qatar GP', '27–29 Nov', '2026-11-29', 57, false, 'scheduled'::f1.race_status),
  (2026, 24, 'abudhabi', 'Abu Dhabi GP', '4–6 Dec', '2026-12-06', 58, false, 'scheduled'::f1.race_status)
on conflict (season_year, round) do update set
  circuit_id        = excluded.circuit_id,
  name              = excluded.name,
  date_label        = excluded.date_label,
  race_date         = coalesce(f1.races.race_date, excluded.race_date),
  scheduled_laps    = excluded.scheduled_laps,
  is_sprint_weekend = excluded.is_sprint_weekend,
  -- never downgrade a race the ETL has already marked completed
  status            = case when f1.races.status = 'completed'
                           then f1.races.status else excluded.status end;


-- ──────────────────────────────────────────────────────────────────────────
-- Make the new views visible to the REST API immediately.
-- ──────────────────────────────────────────────────────────────────────────
notify pgrst, 'reload schema';
