// Generates db/seed/*.sql from the constants still living in index.html.
// Run after editing those constants: npm run seed:gen
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { extractLegacyData } from './extract-legacy.mjs';
import {
  CIRCUIT_TO_ERGAST, TEAM_TO_ERGAST, TEAM_COLORS,
  DRIVER_TO_ERGAST, displayKeyFor, CIRCUIT_TYPE,
} from '../src/mappings.js';

const ROOT = path.resolve(import.meta.dirname, '../..');
const OUT = path.join(ROOT, 'db/seed');

const q = v => v === null || v === undefined || v === ''
  ? 'null'
  : `'${String(v).replace(/'/g, "''")}'`;
const n = v => (v === null || v === undefined || Number.isNaN(Number(v)) ? 'null' : Number(v));

const header = title => `-- ${'='.repeat(74)}
-- ${title}
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ${'='.repeat(74)}\n\n`;

const data = await extractLegacyData();
await mkdir(OUT, { recursive: true });

// ── seasons ────────────────────────────────────────────────────────────────
const years = new Set([2026]);
for (const rc of data.races) for (const y of Object.keys(rc.yr_rounds ?? {})) {
  if (/^\d{4}$/.test(y)) years.add(Number(y));           // skip the "2020b" key
}
const seasonRows = [...years].sort((a, b) => a - b).map(y => `(${y})`);
await writeFile(path.join(OUT, '0010_seasons.sql'),
  header('Seasons') +
  `insert into f1.seasons (year) values\n  ${seasonRows.join(',\n  ')}\n` +
  `on conflict (year) do nothing;\n`);

// ── circuits ───────────────────────────────────────────────────────────────
const circuitRows = data.races.map(rc => `  (${[
  q(rc.k), q(CIRCUIT_TO_ERGAST[rc.k] ?? null), q(rc.c), q(rc.c), q(rc.co),
  q(data.flags[rc.k] ?? null), n(rc.km), n(rc.t),
  `${q(CIRCUIT_TYPE[rc.type] ?? 'permanent')}::f1.circuit_type`,
  q(data.circuitPaths[rc.k] ?? null),
].join(', ')})`);

await writeFile(path.join(OUT, '0011_circuits.sql'),
  header('Circuits — names, geometry and SVG track layouts') +
  `insert into f1.circuits
  (id, ergast_circuit_id, name, locality, country, flag_emoji,
   length_km, turns, circuit_type, svg_path)
values\n${circuitRows.join(',\n')}
on conflict (id) do update set
  ergast_circuit_id = excluded.ergast_circuit_id,
  name              = excluded.name,
  locality          = excluded.locality,
  country           = excluded.country,
  flag_emoji        = excluded.flag_emoji,
  length_km         = excluded.length_km,
  turns             = excluded.turns,
  circuit_type      = excluded.circuit_type,
  svg_path          = excluded.svg_path;\n`);

// ── constructors ───────────────────────────────────────────────────────────
const constructorRows = Object.entries(TEAM_TO_ERGAST).map(([label, id]) =>
  `  (${[q(id), q(label), q(TEAM_COLORS[id] ?? null)].join(', ')})`);

await writeFile(path.join(OUT, '0012_constructors.sql'),
  header('Constructors — display names and livery colours') +
  `insert into f1.constructors (id, name, color)
values\n${constructorRows.join(',\n')}
on conflict (id) do update set
  name  = excluded.name,
  color = coalesce(excluded.color, f1.constructors.color);\n`);

// ── drivers ────────────────────────────────────────────────────────────────
const unmapped = [];
const driverRows = Object.entries(data.drivers).flatMap(([key, d]) => {
  const id = DRIVER_TO_ERGAST[key];
  if (!id) { unmapped.push(key); return []; }
  // `img` is the preferred headshot, `img2` the fallback the page falls back to.
  return [`  (${[
    q(id), q(displayKeyFor(id, key)), q(key), n(d.num),
    q(d.img ?? null), q(d.img2 ?? null),
  ].join(', ')})`];
});
if (unmapped.length) {
  console.error(`\n  drivers with no Ergast id in mappings.js: ${unmapped.join(', ')}`);
  process.exitCode = 1;
}

await writeFile(path.join(OUT, '0013_drivers.sql'),
  header('Drivers — headshots and display keys (names filled in by the ETL)') +
  `insert into f1.drivers
  (id, display_key, family_name, permanent_number, headshot_url, headshot_fallback_url)
values\n${driverRows.join(',\n')}
on conflict (id) do update set
  display_key           = excluded.display_key,
  permanent_number      = coalesce(excluded.permanent_number, f1.drivers.permanent_number),
  headshot_url          = coalesce(excluded.headshot_url, f1.drivers.headshot_url),
  headshot_fallback_url = coalesce(excluded.headshot_fallback_url, f1.drivers.headshot_fallback_url);\n`);

// ── 2026 driver entries ────────────────────────────────────────────────────
// Only the 2026 grid; historic line-ups come from the ETL.
const GRID_2026 = new Set(['Antonelli', 'Russell', 'Leclerc', 'Hamilton', 'Norris',
  'Piastri', 'Verstappen', 'Hadjar', 'Sainz', 'Albon', 'Alonso', 'Stroll',
  'Perez', 'Hulkenberg', 'Ocon', 'Gasly']);
const entryRows = Object.entries(data.drivers)
  .filter(([key]) => GRID_2026.has(key) && DRIVER_TO_ERGAST[key] && TEAM_TO_ERGAST[data.drivers[key].team])
  .map(([key, d]) => `  (2026, ${q(DRIVER_TO_ERGAST[key])}, ${q(TEAM_TO_ERGAST[d.team])}, ${n(d.num)})`);

await writeFile(path.join(OUT, '0014_driver_entries_2026.sql'),
  header('2026 grid — driver / team / car number') +
  `insert into f1.driver_entries (season_year, driver_id, constructor_id, car_number)
values\n${entryRows.join(',\n')}
on conflict (season_year, driver_id, constructor_id) do update set
  car_number = excluded.car_number;\n`);

// ── 2026 calendar ──────────────────────────────────────────────────────────
// Dates the ETL cannot infer (display labels, planned lap counts, sprint flags,
// cancellations) are authored here; results are layered on by the ETL.
const today = new Date().toISOString().slice(0, 10);
const calRows = data.races.map(rc => {
  const status = rc.cancelled ? 'cancelled'
    : rc.end && rc.end < today ? 'completed'
    : 'scheduled';
  return `  (${[
    2026, n(rc.r), q(rc.k), q(rc.n), q(rc.d), q(rc.end ?? null), n(rc.laps),
    rc.sprint ? 'true' : 'false', `${q(status)}::f1.race_status`,
  ].join(', ')})`;
});

await writeFile(path.join(OUT, '0015_races_2026.sql'),
  header('2026 calendar — 24 rounds') +
  `insert into f1.races
  (season_year, round, circuit_id, name, date_label, race_date, scheduled_laps,
   is_sprint_weekend, status)
values\n${calRows.join(',\n')}
on conflict (season_year, round) do update set
  circuit_id        = excluded.circuit_id,
  name              = excluded.name,
  date_label        = excluded.date_label,
  race_date         = coalesce(f1.races.race_date, excluded.race_date),
  scheduled_laps    = excluded.scheduled_laps,
  is_sprint_weekend = excluded.is_sprint_weekend,
  -- never downgrade a race the ETL has already marked completed
  status            = case when f1.races.status = 'completed'
                           then f1.races.status else excluded.status end;\n`);

console.log(`seasons        ${seasonRows.length}
circuits       ${circuitRows.length}
constructors   ${constructorRows.length}
drivers        ${driverRows.length}
2026 entries   ${entryRows.length}
2026 races     ${calRows.length}
-> db/seed/`);
