-- ==========================================================================
-- Circuits — names, location and geometry
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.circuits
  (id, ergast_circuit_id, name, locality, country, flag_emoji,
   length_km, turns, circuit_type)
values
  ('australia', 'albert_park', 'Melbourne', 'Melbourne', 'Australia', '🇦🇺', 5.278, 14, 'street'::f1.circuit_type),
  ('china', 'shanghai', 'Shanghai', 'Shanghai', 'China', '🇨🇳', 5.451, 16, 'permanent'::f1.circuit_type),
  ('japan', 'suzuka', 'Suzuka', 'Suzuka', 'Japan', '🇯🇵', 5.807, 18, 'permanent'::f1.circuit_type),
  ('bahrain', 'bahrain', 'Sakhir', 'Sakhir', 'Bahrain', '🇧🇭', 5.412, 15, 'permanent'::f1.circuit_type),
  ('saudi', 'jeddah', 'Jeddah', 'Jeddah', 'Saudi Arabia', '🇸🇦', 6.174, 27, 'street'::f1.circuit_type),
  ('miami', 'miami', 'Miami Gardens', 'Miami Gardens', 'USA', '🇺🇸', 5.412, 19, 'semi_permanent'::f1.circuit_type),
  ('canada', 'villeneuve', 'Montréal', 'Montréal', 'Canada', '🇨🇦', 4.361, 14, 'semi_permanent'::f1.circuit_type),
  ('monaco', 'monaco', 'Monte Carlo', 'Monte Carlo', 'Monaco', '🇲🇨', 3.337, 19, 'street'::f1.circuit_type),
  ('spain', 'catalunya', 'Barcelona', 'Barcelona', 'Spain', '🇪🇸', 4.675, 14, 'permanent'::f1.circuit_type),
  ('austria', 'red_bull_ring', 'Spielberg', 'Spielberg', 'Austria', '🇦🇹', 4.318, 10, 'permanent'::f1.circuit_type),
  ('britain', 'silverstone', 'Silverstone', 'Silverstone', 'Great Britain', '🇬🇧', 5.891, 18, 'permanent'::f1.circuit_type),
  ('belgium', 'spa', 'Spa-Francorchamps', 'Spa-Francorchamps', 'Belgium', '🇧🇪', 7.004, 19, 'permanent'::f1.circuit_type),
  ('hungary', 'hungaroring', 'Budapest', 'Budapest', 'Hungary', '🇭🇺', 4.381, 14, 'permanent'::f1.circuit_type),
  ('netherlands', 'zandvoort', 'Zandvoort', 'Zandvoort', 'Netherlands', '🇳🇱', 4.259, 14, 'permanent'::f1.circuit_type),
  ('italy', 'monza', 'Monza', 'Monza', 'Italy', '🇮🇹', 5.793, 11, 'permanent'::f1.circuit_type),
  ('madrid', 'madring', 'Madrid', 'Madrid', 'Spain', '🇪🇸', 5.47, 20, 'street'::f1.circuit_type),
  ('azerbaijan', 'baku', 'Baku', 'Baku', 'Azerbaijan', '🇦🇿', 6.003, 20, 'street'::f1.circuit_type),
  ('singapore', 'marina_bay', 'Marina Bay', 'Marina Bay', 'Singapore', '🇸🇬', 4.94, 19, 'street'::f1.circuit_type),
  ('usa', 'americas', 'Austin', 'Austin', 'USA', '🇺🇸', 5.513, 20, 'permanent'::f1.circuit_type),
  ('mexico', 'rodriguez', 'Mexico City', 'Mexico City', 'Mexico', '🇲🇽', 4.304, 17, 'permanent'::f1.circuit_type),
  ('brazil', 'interlagos', 'São Paulo', 'São Paulo', 'Brazil', '🇧🇷', 4.309, 15, 'permanent'::f1.circuit_type),
  ('lasvegas', 'vegas', 'Las Vegas', 'Las Vegas', 'USA', '🇺🇸', 6.201, 17, 'street'::f1.circuit_type),
  ('qatar', 'losail', 'Lusail', 'Lusail', 'Qatar', '🇶🇦', 5.38, 16, 'permanent'::f1.circuit_type),
  ('abudhabi', 'yas_marina', 'Yas Marina', 'Yas Marina', 'UAE', '🇦🇪', 5.281, 16, 'permanent'::f1.circuit_type)
on conflict (id) do update set
  ergast_circuit_id = excluded.ergast_circuit_id,
  name              = excluded.name,
  locality          = excluded.locality,
  country           = excluded.country,
  flag_emoji        = excluded.flag_emoji,
  length_km         = excluded.length_km,
  turns             = excluded.turns,
  circuit_type      = excluded.circuit_type;
