-- ==========================================================================
-- Constructors — display names and livery colours
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.constructors (id, name, color)
values
  ('mercedes', 'Mercedes', '#00D7B6'),
  ('ferrari', 'Ferrari', '#ED1131'),
  ('mclaren', 'McLaren', '#F47600'),
  ('red_bull', 'Red Bull', '#4781D7'),
  ('williams', 'Williams', '#00A0DE'),
  ('aston_martin', 'Aston Martin', '#229971'),
  ('cadillac', 'Cadillac', '#909090'),
  ('audi', 'Audi', '#F50537'),
  ('haas', 'Haas', '#B6BABD'),
  ('alpine', 'Alpine', '#00A1E8'),
  ('rb', 'RB', '#6692FF'),
  ('alfa', 'Alfa Romeo', '#900000'),
  ('force_india', 'Force India', '#FF80C7'),
  ('renault', 'Renault', '#FFF500'),
  ('bar', 'BAR', '#D40000'),
  ('jordan', 'Jordan', '#FFD700'),
  ('bmw_sauber', 'BMW', '#0055A5'),
  ('brawn', 'Brawn GP', '#B8FD6E')
on conflict (id) do update set
  name  = excluded.name,
  color = coalesce(excluded.color, f1.constructors.color);
