-- ==========================================================================
-- 2026 grid — driver / team / car number
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.driver_entries (season_year, driver_id, constructor_id, car_number)
values
  (2026, 'antonelli', 'mercedes', 12),
  (2026, 'russell', 'mercedes', 63),
  (2026, 'leclerc', 'ferrari', 16),
  (2026, 'hamilton', 'ferrari', 44),
  (2026, 'norris', 'mclaren', 1),
  (2026, 'piastri', 'mclaren', 81),
  (2026, 'max_verstappen', 'red_bull', 3),
  (2026, 'hadjar', 'red_bull', 6),
  (2026, 'sainz', 'williams', 55),
  (2026, 'alonso', 'aston_martin', 14),
  (2026, 'perez', 'cadillac', 11),
  (2026, 'hulkenberg', 'audi', 27),
  (2026, 'ocon', 'haas', 31),
  (2026, 'gasly', 'alpine', 10),
  (2026, 'albon', 'williams', 23),
  (2026, 'stroll', 'aston_martin', 18)
on conflict (season_year, driver_id, constructor_id) do update set
  car_number = excluded.car_number;
