-- ==========================================================================
-- 2026 calendar — 24 rounds
-- GENERATED by etl/scripts/gen-seed.mjs — do not edit by hand.
-- ==========================================================================

insert into f1.races
  (season_year, round, circuit_id, name, date_label, race_date, scheduled_laps,
   is_sprint_weekend, status)
values
  (2026, 1, 'australia', 'Australian GP', '6–8 Mar', '2026-03-08', 58, false, 'completed'::f1.race_status),
  (2026, 2, 'china', 'Chinese GP', '13–15 Mar', '2026-03-15', 56, true, 'completed'::f1.race_status),
  (2026, 3, 'japan', 'Japanese GP', '27–29 Mar', '2026-03-29', 53, false, 'completed'::f1.race_status),
  (2026, 4, 'bahrain', 'Bahrain GP', '10–12 Apr', '2026-04-12', 57, false, 'cancelled'::f1.race_status),
  (2026, 5, 'saudi', 'Saudi Arabian GP', '17–19 Apr', '2026-04-19', 50, false, 'cancelled'::f1.race_status),
  (2026, 6, 'miami', 'Miami GP', '1–3 May', '2026-05-03', 57, true, 'completed'::f1.race_status),
  (2026, 7, 'canada', 'Canadian GP', '22–24 May', '2026-05-24', 70, true, 'completed'::f1.race_status),
  (2026, 8, 'monaco', 'Monaco GP', '5–7 Jun', '2026-06-07', 78, false, 'completed'::f1.race_status),
  (2026, 9, 'spain', 'Barcelona-Catalunya GP', '12–14 Jun', '2026-06-14', 66, false, 'completed'::f1.race_status),
  (2026, 10, 'austria', 'Austrian GP', '26–28 Jun', '2026-06-28', 71, false, 'completed'::f1.race_status),
  (2026, 11, 'britain', 'British GP', '3–5 Jul', '2026-07-05', 52, true, 'completed'::f1.race_status),
  (2026, 12, 'belgium', 'Belgian GP', '17–19 Jul', '2026-07-19', 44, false, 'completed'::f1.race_status),
  (2026, 13, 'hungary', 'Hungarian GP', '24–26 Jul', '2026-07-26', 70, false, 'completed'::f1.race_status),
  (2026, 14, 'netherlands', 'Dutch GP', '21–23 Aug', '2026-08-23', 72, true, 'completed'::f1.race_status),
  (2026, 15, 'italy', 'Italian GP', '4–6 Sep', '2026-09-06', 53, false, 'completed'::f1.race_status),
  (2026, 16, 'madrid', 'Madrid GP', '11–13 Sep', '2026-09-13', 56, false, 'completed'::f1.race_status),
  (2026, 17, 'azerbaijan', 'Azerbaijan GP', '25–27 Sep', '2026-09-27', 51, false, 'scheduled'::f1.race_status),
  (2026, 18, 'singapore', 'Singapore GP', '9–11 Oct', '2026-10-11', 62, true, 'scheduled'::f1.race_status),
  (2026, 19, 'usa', 'US GP', '23–25 Oct', '2026-10-25', 56, false, 'scheduled'::f1.race_status),
  (2026, 20, 'mexico', 'Mexico City GP', '30 Oct–1 Nov', '2026-11-01', 71, false, 'scheduled'::f1.race_status),
  (2026, 21, 'brazil', 'Brazilian GP', '6–8 Nov', '2026-11-08', 71, false, 'scheduled'::f1.race_status),
  (2026, 22, 'lasvegas', 'Las Vegas GP', '19–21 Nov', '2026-11-21', 50, false, 'scheduled'::f1.race_status),
  (2026, 23, 'qatar', 'Qatar GP', '27–29 Nov', '2026-11-29', 57, false, 'scheduled'::f1.race_status),
  (2026, 24, 'abudhabi', 'Abu Dhabi GP', '4–6 Dec', '2026-12-06', 58, false, 'scheduled'::f1.race_status)
on conflict (season_year, round) do update set
  circuit_id        = excluded.circuit_id,
  name              = excluded.name,
  date_label        = excluded.date_label,
  race_date         = coalesce(f1.races.race_date, excluded.race_date),
  scheduled_laps    = excluded.scheduled_laps,
  is_sprint_weekend = excluded.is_sprint_weekend,
  -- never downgrade a race the ETL has already marked completed
  status            = case when f1.races.status = 'completed'
                           then f1.races.status else excluded.status end;
